language: node_js

script:
  - npm run lint
  - npm run test
  - npm run build

notifications:
  slack:
    secure: QxxoUzmxZMZ+WM0q6gjHMHlYmt0ni/cx42oDHek/XjHw8fFiaeWED5t0n8M/GkvgJkNP9SiZNGI33hCgUFSt6BzTfR99YHI4UWaQYTtcbLbgC86FP7SnLBUuC/8Q78vj1UU8Qk6Tk1AQVh+XCl94MAMuJZg6r4KTfVREkGUEIM0/0yNk5luFOkuEC30H1q7mLHJ+fFmFfur2WvjwPL7KcyP/aVMpUrrnmBmsaZn1YPfTq4C3mgX2PhnXX297567FNNcUH7thrtmu0dQEuNM6F1bQHHmyTJc26qelo+F/2zeKHN6NXlWgnuQxD//ZPNMxlcNMpRjBzyTsWvZAQ1yGO2LtV6Ds2eYLBq3+8+BwQriyLxuI/rJatpgGDqEr4sfykZi+qrsdE0mA2gUvWlvYzDO+0jG3wu/stjajOJR22nqeCoIlUDj/ANNvb8VXJPA6oZgm5bVSicb1CknxeiUH5feIAz5AKpE9w8kSUr6lgPdZr5RYcWJ8Q3QQjwr+Bps2/zn/MVn9EUlyp+VeT31f273fev5ldruEfJf8yZadk9lQ7OBJiXWbtEsMsTZx6bXPfbgNac3dM+39KxS1P9QFGx1qsnSY6xLyS5nxRlJWWpaLWxJMMnuMwnUID/11ylUcuWJO37dE6V9w+cNMQfgve1Ztv4LetyUtDisL2OYVe3w=
