docsPath: ./docs
distPath: ./sitedist

# https://www.gatsbyjs.org/docs/gatsby-config
config:
  siteMetadata:
    title: playable
  pathPrefix: /playable
  algoliaApiKey: 8b7e07f448cec6e39fa301bf82ac83d6
  githubLink: https://github.com/wix/playable

navigation:
  - path: /player-config
    title: Configuration
  - path: /video-source
    title: Video source
  - path: /api
    title: API reference
  - path: /modules
    title: Modules
  - path: /events
    title: Player events
  - path: /adapters
    title: Playback adapters
